// Code generated by MockGen. DO NOT EDIT.
// Source: d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\email-service\internal\service\email_service.go
//
// Generated by this command:
//
//	mockgen -source=d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\email-service\internal\service\email_service.go -destination=d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\email-service\test\unit\mock\mock_email_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "furab-backend/services/email-service/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmailSender is a mock of EmailSender interface.
type MockEmailSender struct {
	ctrl     *gomock.Controller
	recorder *MockEmailSenderMockRecorder
	isgomock struct{}
}

// MockEmailSenderMockRecorder is the mock recorder for MockEmailSender.
type MockEmailSenderMockRecorder struct {
	mock *MockEmailSender
}

// NewMockEmailSender creates a new mock instance.
func NewMockEmailSender(ctrl *gomock.Controller) *MockEmailSender {
	mock := &MockEmailSender{ctrl: ctrl}
	mock.recorder = &MockEmailSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailSender) EXPECT() *MockEmailSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockEmailSender) Send(ctx context.Context, receiverEmail, subject, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, receiverEmail, subject, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockEmailSenderMockRecorder) Send(ctx, receiverEmail, subject, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockEmailSender)(nil).Send), ctx, receiverEmail, subject, body)
}

// MockEmailService is a mock of EmailService interface.
type MockEmailService struct {
	ctrl     *gomock.Controller
	recorder *MockEmailServiceMockRecorder
	isgomock struct{}
}

// MockEmailServiceMockRecorder is the mock recorder for MockEmailService.
type MockEmailServiceMockRecorder struct {
	mock *MockEmailService
}

// NewMockEmailService creates a new mock instance.
func NewMockEmailService(ctrl *gomock.Controller) *MockEmailService {
	mock := &MockEmailService{ctrl: ctrl}
	mock.recorder = &MockEmailServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailService) EXPECT() *MockEmailServiceMockRecorder {
	return m.recorder
}

// SendEmail mocks base method.
func (m *MockEmailService) SendEmail(ctx context.Context, req model.SendEmailRequest) (*model.EmailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", ctx, req)
	ret0, _ := ret[0].(*model.EmailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockEmailServiceMockRecorder) SendEmail(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockEmailService)(nil).SendEmail), ctx, req)
}

// SendEmailWithResult mocks base method.
func (m *MockEmailService) SendEmailWithResult(ctx context.Context, req model.SendEmailRequest) (*model.EmailResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmailWithResult", ctx, req)
	ret0, _ := ret[0].(*model.EmailResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendEmailWithResult indicates an expected call of SendEmailWithResult.
func (mr *MockEmailServiceMockRecorder) SendEmailWithResult(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmailWithResult", reflect.TypeOf((*MockEmailService)(nil).SendEmailWithResult), ctx, req)
}

// TriggerEventEmail mocks base method.
func (m *MockEmailService) TriggerEventEmail(ctx context.Context, req model.EventEmailRequest) (*model.EmailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerEventEmail", ctx, req)
	ret0, _ := ret[0].(*model.EmailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerEventEmail indicates an expected call of TriggerEventEmail.
func (mr *MockEmailServiceMockRecorder) TriggerEventEmail(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerEventEmail", reflect.TypeOf((*MockEmailService)(nil).TriggerEventEmail), ctx, req)
}
