// Code generated by MockGen. DO NOT EDIT.
// Source: d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\email-service\internal\repository\email_repository.go
//
// Generated by this command:
//
//	mockgen -source=d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\email-service\internal\repository\email_repository.go -destination=d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\email-service\test\unit\mock\mock_email_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "furab-backend/services/email-service/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmailRepository is a mock of EmailRepository interface.
type MockEmailRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmailRepositoryMockRecorder
	isgomock struct{}
}

// MockEmailRepositoryMockRecorder is the mock recorder for MockEmailRepository.
type MockEmailRepositoryMockRecorder struct {
	mock *MockEmailRepository
}

// NewMockEmailRepository creates a new mock instance.
func NewMockEmailRepository(ctrl *gomock.Controller) *MockEmailRepository {
	mock := &MockEmailRepository{ctrl: ctrl}
	mock.recorder = &MockEmailRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailRepository) EXPECT() *MockEmailRepositoryMockRecorder {
	return m.recorder
}

// GetTemplateByID mocks base method.
func (m *MockEmailRepository) GetTemplateByID(ctx context.Context, templateID string) (*model.EmailTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateByID", ctx, templateID)
	ret0, _ := ret[0].(*model.EmailTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplateByID indicates an expected call of GetTemplateByID.
func (mr *MockEmailRepositoryMockRecorder) GetTemplateByID(ctx, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateByID", reflect.TypeOf((*MockEmailRepository)(nil).GetTemplateByID), ctx, templateID)
}

// SaveEmailLog mocks base method.
func (m *MockEmailRepository) SaveEmailLog(ctx context.Context, log model.EmailLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEmailLog", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEmailLog indicates an expected call of SaveEmailLog.
func (mr *MockEmailRepositoryMockRecorder) SaveEmailLog(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEmailLog", reflect.TypeOf((*MockEmailRepository)(nil).SaveEmailLog), ctx, log)
}
