// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/driver_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/driver_repository.go -destination=internal/repository/mock/mock_driver_repository.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	"context"
	"reflect"

	"furab-backend/services/driver-service/internal/model"

	"go.uber.org/mock/gomock"
)

// MockDriverRepository is a mock of DriverRepository interface.
type MockDriverRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDriverRepositoryMockRecorder
	isgomock struct{}
}

// MockDriverRepositoryMockRecorder is the mock recorder for MockDriverRepository.
type MockDriverRepositoryMockRecorder struct {
	mock *MockDriverRepository
}

// NewMockDriverRepository creates a new mock instance.
func NewMockDriverRepository(ctrl *gomock.Controller) *MockDriverRepository {
	mock := &MockDriverRepository{ctrl: ctrl}
	mock.recorder = &MockDriverRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriverRepository) EXPECT() *MockDriverRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockDriverRepository) Save(ctx context.Context, driver *model.Driver) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, driver)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockDriverRepositoryMockRecorder) Save(ctx, driver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockDriverRepository)(nil).Save), ctx, driver)
}

// FindByID mocks base method.
func (m *MockDriverRepository) FindByID(ctx context.Context, driverID string) (*model.Driver, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, driverID)
	ret0, _ := ret[0].(*model.Driver)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockDriverRepositoryMockRecorder) FindByID(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockDriverRepository)(nil).FindByID), ctx, driverID)
}

// Update mocks base method.
func (m *MockDriverRepository) Update(ctx context.Context, driver *model.Driver) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, driver)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDriverRepositoryMockRecorder) Update(ctx, driver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDriverRepository)(nil).Update), ctx, driver)
}

// UpdateStatus mocks base method.
func (m *MockDriverRepository) UpdateStatus(ctx context.Context, driverID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, driverID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockDriverRepositoryMockRecorder) UpdateStatus(ctx, driverID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockDriverRepository)(nil).UpdateStatus), ctx, driverID, status)
}

// UpdateLocation mocks base method.
func (m *MockDriverRepository) UpdateLocation(ctx context.Context, driverID string, lat, long float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLocation", ctx, driverID, lat, long)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLocation indicates an expected call of UpdateLocation.
func (mr *MockDriverRepositoryMockRecorder) UpdateLocation(ctx, driverID, lat, long any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLocation", reflect.TypeOf((*MockDriverRepository)(nil).UpdateLocation), ctx, driverID, lat, long)
}
