apiVersion: v1
kind: Service
metadata:
  name: ride-order-service
  namespace: furab
  labels:
    app: ride-order-service
    app.kubernetes.io/name: ride-order-service
    app.kubernetes.io/part-of: furab
spec:
  type: ClusterIP
  selector:
    app: ride-order-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
