// Code generated by MockGen. DO NOT EDIT.
// Source: d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\notification-service\internal\service\notification_service.go
//
// Generated by this command:
//
//	mockgen -source=d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\notification-service\internal\service\notification_service.go -destination=d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\notification-service\test\unit\mock\mock_notification_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "furab-backend/services/notification-service/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmailClient is a mock of EmailClient interface.
type MockEmailClient struct {
	ctrl     *gomock.Controller
	recorder *MockEmailClientMockRecorder
	isgomock struct{}
}

// MockEmailClientMockRecorder is the mock recorder for MockEmailClient.
type MockEmailClientMockRecorder struct {
	mock *MockEmailClient
}

// NewMockEmailClient creates a new mock instance.
func NewMockEmailClient(ctrl *gomock.Controller) *MockEmailClient {
	mock := &MockEmailClient{ctrl: ctrl}
	mock.recorder = &MockEmailClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailClient) EXPECT() *MockEmailClientMockRecorder {
	return m.recorder
}

// SendEmail mocks base method.
func (m *MockEmailClient) SendEmail(ctx context.Context, receiverID, title, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", ctx, receiverID, title, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockEmailClientMockRecorder) SendEmail(ctx, receiverID, title, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockEmailClient)(nil).SendEmail), ctx, receiverID, title, message)
}

// MockNotificationService is a mock of NotificationService interface.
type MockNotificationService struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationServiceMockRecorder
	isgomock struct{}
}

// MockNotificationServiceMockRecorder is the mock recorder for MockNotificationService.
type MockNotificationServiceMockRecorder struct {
	mock *MockNotificationService
}

// NewMockNotificationService creates a new mock instance.
func NewMockNotificationService(ctrl *gomock.Controller) *MockNotificationService {
	mock := &MockNotificationService{ctrl: ctrl}
	mock.recorder = &MockNotificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationService) EXPECT() *MockNotificationServiceMockRecorder {
	return m.recorder
}

// GenerateNotificationTemplate mocks base method.
func (m *MockNotificationService) GenerateNotificationTemplate(ctx context.Context, eventType string) (*model.NotifTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateNotificationTemplate", ctx, eventType)
	ret0, _ := ret[0].(*model.NotifTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateNotificationTemplate indicates an expected call of GenerateNotificationTemplate.
func (mr *MockNotificationServiceMockRecorder) GenerateNotificationTemplate(ctx, eventType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateNotificationTemplate", reflect.TypeOf((*MockNotificationService)(nil).GenerateNotificationTemplate), ctx, eventType)
}

// SendNotification mocks base method.
func (m *MockNotificationService) SendNotification(ctx context.Context, req model.EventNotificationRequest) (*model.NotificationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNotification", ctx, req)
	ret0, _ := ret[0].(*model.NotificationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendNotification indicates an expected call of SendNotification.
func (mr *MockNotificationServiceMockRecorder) SendNotification(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNotification", reflect.TypeOf((*MockNotificationService)(nil).SendNotification), ctx, req)
}
