// Code generated by MockGen. DO NOT EDIT.
// Source: d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\notification-service\internal\repository\notification_repository.go
//
// Generated by this command:
//
//	mockgen -source=d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\notification-service\internal\repository\notification_repository.go -destination=d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\notification-service\test\unit\mock\mock_notification_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "furab-backend/services/notification-service/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNotificationRepository is a mock of NotificationRepository interface.
type MockNotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepositoryMockRecorder
	isgomock struct{}
}

// MockNotificationRepositoryMockRecorder is the mock recorder for MockNotificationRepository.
type MockNotificationRepositoryMockRecorder struct {
	mock *MockNotificationRepository
}

// NewMockNotificationRepository creates a new mock instance.
func NewMockNotificationRepository(ctrl *gomock.Controller) *MockNotificationRepository {
	mock := &MockNotificationRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepository) EXPECT() *MockNotificationRepositoryMockRecorder {
	return m.recorder
}

// GetTemplateByEventType mocks base method.
func (m *MockNotificationRepository) GetTemplateByEventType(ctx context.Context, eventType string) (*model.NotifTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateByEventType", ctx, eventType)
	ret0, _ := ret[0].(*model.NotifTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplateByEventType indicates an expected call of GetTemplateByEventType.
func (mr *MockNotificationRepositoryMockRecorder) GetTemplateByEventType(ctx, eventType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateByEventType", reflect.TypeOf((*MockNotificationRepository)(nil).GetTemplateByEventType), ctx, eventType)
}

// SaveNotificationLog mocks base method.
func (m *MockNotificationRepository) SaveNotificationLog(ctx context.Context, log model.NotificationLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveNotificationLog", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveNotificationLog indicates an expected call of SaveNotificationLog.
func (mr *MockNotificationRepositoryMockRecorder) SaveNotificationLog(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveNotificationLog", reflect.TypeOf((*MockNotificationRepository)(nil).SaveNotificationLog), ctx, log)
}
