// Code generated by MockGen. DO NOT EDIT.
// Source: ../../internal/repository/merchant_repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "furab-backend/services/merchant-service/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMerchantRepository is a mock of MerchantRepository interface.
type MockMerchantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMerchantRepositoryMockRecorder
}

// MockMerchantRepositoryMockRecorder is the mock recorder for MockMerchantRepository.
type MockMerchantRepositoryMockRecorder struct {
	mock *MockMerchantRepository
}

// NewMockMerchantRepository creates a new mock instance.
func NewMockMerchantRepository(ctrl *gomock.Controller) *MockMerchantRepository {
	mock := &MockMerchantRepository{ctrl: ctrl}
	mock.recorder = &MockMerchantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMerchantRepository) EXPECT() *MockMerchantRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockMerchantRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMerchantRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMerchantRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockMerchantRepository) GetByID(ctx context.Context, id string) (*model.Merchant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Merchant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMerchantRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMerchantRepository)(nil).GetByID), ctx, id)
}

// Save mocks base method.
func (m *MockMerchantRepository) Save(ctx context.Context, merchant *model.Merchant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, merchant)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockMerchantRepositoryMockRecorder) Save(ctx, merchant interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockMerchantRepository)(nil).Save), ctx, merchant)
}

// Search mocks base method.
func (m *MockMerchantRepository) Search(ctx context.Context, req model.SearchMerchantRequest) ([]model.Merchant, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, req)
	ret0, _ := ret[0].([]model.Merchant)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Search indicates an expected call of Search.
func (mr *MockMerchantRepositoryMockRecorder) Search(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockMerchantRepository)(nil).Search), ctx, req)
}

// Update mocks base method.
func (m *MockMerchantRepository) Update(ctx context.Context, merchant *model.Merchant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, merchant)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMerchantRepositoryMockRecorder) Update(ctx, merchant interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMerchantRepository)(nil).Update), ctx, merchant)
}
