// Code generated by MockGen. DO NOT EDIT.
// Source: location_repository.go
//
// Generated by this command:
//
//	mockgen -source location_repository.go -destination mock_repository/mock_location_repository.go -package mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	model "furab-backend/services/location-service/internal/model"
	reflect "reflect"

	redis "github.com/redis/go-redis/v9"
	gomock "go.uber.org/mock/gomock"
)

// MockLocationRepository is a mock of LocationRepository interface.
type MockLocationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLocationRepositoryMockRecorder
	isgomock struct{}
}

// MockLocationRepositoryMockRecorder is the mock recorder for MockLocationRepository.
type MockLocationRepositoryMockRecorder struct {
	mock *MockLocationRepository
}

// NewMockLocationRepository creates a new mock instance.
func NewMockLocationRepository(ctrl *gomock.Controller) *MockLocationRepository {
	mock := &MockLocationRepository{ctrl: ctrl}
	mock.recorder = &MockLocationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocationRepository) EXPECT() *MockLocationRepositoryMockRecorder {
	return m.recorder
}

// GetStatus mocks base method.
func (m *MockLocationRepository) GetStatus(ctx context.Context, driverID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, driverID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockLocationRepositoryMockRecorder) GetStatus(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockLocationRepository)(nil).GetStatus), ctx, driverID)
}

// IsDriverActive mocks base method.
func (m *MockLocationRepository) IsDriverActive(ctx context.Context, driverID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDriverActive", ctx, driverID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsDriverActive indicates an expected call of IsDriverActive.
func (mr *MockLocationRepositoryMockRecorder) IsDriverActive(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDriverActive", reflect.TypeOf((*MockLocationRepository)(nil).IsDriverActive), ctx, driverID)
}

// SearchNearbyDrivers mocks base method.
func (m *MockLocationRepository) SearchNearbyDrivers(ctx context.Context, req model.SearchDriverRequest) ([]redis.GeoLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchNearbyDrivers", ctx, req)
	ret0, _ := ret[0].([]redis.GeoLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchNearbyDrivers indicates an expected call of SearchNearbyDrivers.
func (mr *MockLocationRepositoryMockRecorder) SearchNearbyDrivers(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchNearbyDrivers", reflect.TypeOf((*MockLocationRepository)(nil).SearchNearbyDrivers), ctx, req)
}

// TrackDriver mocks base method.
func (m *MockLocationRepository) TrackDriver(ctx context.Context, driverID string) (*model.TrackLocationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackDriver", ctx, driverID)
	ret0, _ := ret[0].(*model.TrackLocationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TrackDriver indicates an expected call of TrackDriver.
func (mr *MockLocationRepositoryMockRecorder) TrackDriver(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackDriver", reflect.TypeOf((*MockLocationRepository)(nil).TrackDriver), ctx, driverID)
}

// UpdateLocation mocks base method.
func (m *MockLocationRepository) UpdateLocation(ctx context.Context, req model.UpdateLocationRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLocation", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLocation indicates an expected call of UpdateLocation.
func (mr *MockLocationRepositoryMockRecorder) UpdateLocation(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLocation", reflect.TypeOf((*MockLocationRepository)(nil).UpdateLocation), ctx, req)
}

// UpdateStatus mocks base method.
func (m *MockLocationRepository) UpdateStatus(ctx context.Context, req model.UpdateStatusRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockLocationRepositoryMockRecorder) UpdateStatus(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockLocationRepository)(nil).UpdateStatus), ctx, req)
}
