// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/chat_repository.go
//
// Generated by this command:
//
//	mockgen -source internal/repository/chat_repository.go -destination internal/repository/mock_repository/mock_chat_repository.go -package mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	model "furab-backend/services/chat-service/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockChatRepository is a mock of ChatRepository interface.
type MockChatRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChatRepositoryMockRecorder
	isgomock struct{}
}

// MockChatRepositoryMockRecorder is the mock recorder for MockChatRepository.
type MockChatRepositoryMockRecorder struct {
	mock *MockChatRepository
}

// NewMockChatRepository creates a new mock instance.
func NewMockChatRepository(ctrl *gomock.Controller) *MockChatRepository {
	mock := &MockChatRepository{ctrl: ctrl}
	mock.recorder = &MockChatRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatRepository) EXPECT() *MockChatRepositoryMockRecorder {
	return m.recorder
}

// GetChatSession mocks base method.
func (m *MockChatRepository) GetChatSession(ctx context.Context, orderID string) (*model.ChatSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatSession", ctx, orderID)
	ret0, _ := ret[0].(*model.ChatSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatSession indicates an expected call of GetChatSession.
func (mr *MockChatRepositoryMockRecorder) GetChatSession(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatSession", reflect.TypeOf((*MockChatRepository)(nil).GetChatSession), ctx, orderID)
}

// GetMessagesByOrderID mocks base method.
func (m *MockChatRepository) GetMessagesByOrderID(ctx context.Context, orderID string) ([]model.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesByOrderID", ctx, orderID)
	ret0, _ := ret[0].([]model.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesByOrderID indicates an expected call of GetMessagesByOrderID.
func (mr *MockChatRepositoryMockRecorder) GetMessagesByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesByOrderID", reflect.TypeOf((*MockChatRepository)(nil).GetMessagesByOrderID), ctx, orderID)
}

// SaveMessage mocks base method.
func (m *MockChatRepository) SaveMessage(ctx context.Context, msg model.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessage", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMessage indicates an expected call of SaveMessage.
func (mr *MockChatRepositoryMockRecorder) SaveMessage(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessage", reflect.TypeOf((*MockChatRepository)(nil).SaveMessage), ctx, msg)
}

// UpdateMessageStatus mocks base method.
func (m *MockChatRepository) UpdateMessageStatus(ctx context.Context, messageID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMessageStatus", ctx, messageID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMessageStatus indicates an expected call of UpdateMessageStatus.
func (mr *MockChatRepositoryMockRecorder) UpdateMessageStatus(ctx, messageID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMessageStatus", reflect.TypeOf((*MockChatRepository)(nil).UpdateMessageStatus), ctx, messageID, status)
}
