// Code generated by MockGen. DO NOT EDIT.
// Source: furab-backend/services/pricing-service/internal/client (interfaces: LocationClient)
//
// Generated by this command:
//
//	mockgen -destination=test\unit\mock\location_client_mock.go -package=mock furab-backend/services/pricing-service/internal/client LocationClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLocationClient is a mock of LocationClient interface.
type MockLocationClient struct {
	ctrl     *gomock.Controller
	recorder *MockLocationClientMockRecorder
	isgomock struct{}
}

// MockLocationClientMockRecorder is the mock recorder for MockLocationClient.
type MockLocationClientMockRecorder struct {
	mock *MockLocationClient
}

// NewMockLocationClient creates a new mock instance.
func NewMockLocationClient(ctrl *gomock.Controller) *MockLocationClient {
	mock := &MockLocationClient{ctrl: ctrl}
	mock.recorder = &MockLocationClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocationClient) EXPECT() *MockLocationClientMockRecorder {
	return m.recorder
}

// GetDeliveryDistance mocks base method.
func (m *MockLocationClient) GetDeliveryDistance(ctx context.Context, orderID string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeliveryDistance", ctx, orderID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeliveryDistance indicates an expected call of GetDeliveryDistance.
func (mr *MockLocationClientMockRecorder) GetDeliveryDistance(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeliveryDistance", reflect.TypeOf((*MockLocationClient)(nil).GetDeliveryDistance), ctx, orderID)
}
