// Code generated by MockGen. DO NOT EDIT.
// Source: furab-backend/services/pricing-service/internal/client (interfaces: OrderClient)
//
// Generated by this command:
//
//	mockgen -destination=test\unit\mock\order_client_mock.go -package=mock furab-backend/services/pricing-service/internal/client OrderClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "furab-backend/services/pricing-service/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrderClient is a mock of OrderClient interface.
type MockOrderClient struct {
	ctrl     *gomock.Controller
	recorder *MockOrderClientMockRecorder
	isgomock struct{}
}

// MockOrderClientMockRecorder is the mock recorder for MockOrderClient.
type MockOrderClientMockRecorder struct {
	mock *MockOrderClient
}

// NewMockOrderClient creates a new mock instance.
func NewMockOrderClient(ctrl *gomock.Controller) *MockOrderClient {
	mock := &MockOrderClient{ctrl: ctrl}
	mock.recorder = &MockOrderClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderClient) EXPECT() *MockOrderClientMockRecorder {
	return m.recorder
}

// GetOrderItems mocks base method.
func (m *MockOrderClient) GetOrderItems(ctx context.Context, orderID string) ([]model.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderItems", ctx, orderID)
	ret0, _ := ret[0].([]model.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderItems indicates an expected call of GetOrderItems.
func (mr *MockOrderClientMockRecorder) GetOrderItems(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderItems", reflect.TypeOf((*MockOrderClient)(nil).GetOrderItems), ctx, orderID)
}
