// Code generated by MockGen. DO NOT EDIT.
// Source: d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\chat-service\internal\service\chat_service.go
//
// Generated by this command:
//
//	mockgen -source=d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\chat-service\internal\service\chat_service.go -destination=d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\chat-service\test\unit\mock\mock_chat_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "furab-backend/services/chat-service/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockChatRepository is a mock of ChatRepository interface.
type MockChatRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChatRepositoryMockRecorder
	isgomock struct{}
}

// MockChatRepositoryMockRecorder is the mock recorder for MockChatRepository.
type MockChatRepositoryMockRecorder struct {
	mock *MockChatRepository
}

// NewMockChatRepository creates a new mock instance.
func NewMockChatRepository(ctrl *gomock.Controller) *MockChatRepository {
	mock := &MockChatRepository{ctrl: ctrl}
	mock.recorder = &MockChatRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatRepository) EXPECT() *MockChatRepositoryMockRecorder {
	return m.recorder
}

// CloseSession mocks base method.
func (m *MockChatRepository) CloseSession(ctx context.Context, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSession", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSession indicates an expected call of CloseSession.
func (mr *MockChatRepositoryMockRecorder) CloseSession(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSession", reflect.TypeOf((*MockChatRepository)(nil).CloseSession), ctx, orderID)
}

// GetMessagesByOrderID mocks base method.
func (m *MockChatRepository) GetMessagesByOrderID(ctx context.Context, orderID string) ([]model.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesByOrderID", ctx, orderID)
	ret0, _ := ret[0].([]model.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesByOrderID indicates an expected call of GetMessagesByOrderID.
func (mr *MockChatRepositoryMockRecorder) GetMessagesByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesByOrderID", reflect.TypeOf((*MockChatRepository)(nil).GetMessagesByOrderID), ctx, orderID)
}

// SaveMessage mocks base method.
func (m *MockChatRepository) SaveMessage(ctx context.Context, msg *model.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessage", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMessage indicates an expected call of SaveMessage.
func (mr *MockChatRepositoryMockRecorder) SaveMessage(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessage", reflect.TypeOf((*MockChatRepository)(nil).SaveMessage), ctx, msg)
}

// UpdateMessageStatus mocks base method.
func (m *MockChatRepository) UpdateMessageStatus(ctx context.Context, messageID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMessageStatus", ctx, messageID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMessageStatus indicates an expected call of UpdateMessageStatus.
func (mr *MockChatRepositoryMockRecorder) UpdateMessageStatus(ctx, messageID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMessageStatus", reflect.TypeOf((*MockChatRepository)(nil).UpdateMessageStatus), ctx, messageID, status)
}

// MockUserServiceClient is a mock of UserServiceClient interface.
type MockUserServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceClientMockRecorder
	isgomock struct{}
}

// MockUserServiceClientMockRecorder is the mock recorder for MockUserServiceClient.
type MockUserServiceClientMockRecorder struct {
	mock *MockUserServiceClient
}

// NewMockUserServiceClient creates a new mock instance.
func NewMockUserServiceClient(ctrl *gomock.Controller) *MockUserServiceClient {
	mock := &MockUserServiceClient{ctrl: ctrl}
	mock.recorder = &MockUserServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceClient) EXPECT() *MockUserServiceClientMockRecorder {
	return m.recorder
}

// ValidateUser mocks base method.
func (m *MockUserServiceClient) ValidateUser(ctx context.Context, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateUser", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateUser indicates an expected call of ValidateUser.
func (mr *MockUserServiceClientMockRecorder) ValidateUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUser", reflect.TypeOf((*MockUserServiceClient)(nil).ValidateUser), ctx, userID)
}

// MockDriverServiceClient is a mock of DriverServiceClient interface.
type MockDriverServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockDriverServiceClientMockRecorder
	isgomock struct{}
}

// MockDriverServiceClientMockRecorder is the mock recorder for MockDriverServiceClient.
type MockDriverServiceClientMockRecorder struct {
	mock *MockDriverServiceClient
}

// NewMockDriverServiceClient creates a new mock instance.
func NewMockDriverServiceClient(ctrl *gomock.Controller) *MockDriverServiceClient {
	mock := &MockDriverServiceClient{ctrl: ctrl}
	mock.recorder = &MockDriverServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriverServiceClient) EXPECT() *MockDriverServiceClientMockRecorder {
	return m.recorder
}

// ValidateDriver mocks base method.
func (m *MockDriverServiceClient) ValidateDriver(ctx context.Context, driverID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateDriver", ctx, driverID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateDriver indicates an expected call of ValidateDriver.
func (mr *MockDriverServiceClientMockRecorder) ValidateDriver(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateDriver", reflect.TypeOf((*MockDriverServiceClient)(nil).ValidateDriver), ctx, driverID)
}

// MockNotificationClient is a mock of NotificationClient interface.
type MockNotificationClient struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationClientMockRecorder
	isgomock struct{}
}

// MockNotificationClientMockRecorder is the mock recorder for MockNotificationClient.
type MockNotificationClientMockRecorder struct {
	mock *MockNotificationClient
}

// NewMockNotificationClient creates a new mock instance.
func NewMockNotificationClient(ctrl *gomock.Controller) *MockNotificationClient {
	mock := &MockNotificationClient{ctrl: ctrl}
	mock.recorder = &MockNotificationClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationClient) EXPECT() *MockNotificationClientMockRecorder {
	return m.recorder
}

// SendNotification mocks base method.
func (m *MockNotificationClient) SendNotification(ctx context.Context, receiverID, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNotification", ctx, receiverID, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendNotification indicates an expected call of SendNotification.
func (mr *MockNotificationClientMockRecorder) SendNotification(ctx, receiverID, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNotification", reflect.TypeOf((*MockNotificationClient)(nil).SendNotification), ctx, receiverID, message)
}

// MockChatService is a mock of ChatService interface.
type MockChatService struct {
	ctrl     *gomock.Controller
	recorder *MockChatServiceMockRecorder
	isgomock struct{}
}

// MockChatServiceMockRecorder is the mock recorder for MockChatService.
type MockChatServiceMockRecorder struct {
	mock *MockChatService
}

// NewMockChatService creates a new mock instance.
func NewMockChatService(ctrl *gomock.Controller) *MockChatService {
	mock := &MockChatService{ctrl: ctrl}
	mock.recorder = &MockChatServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatService) EXPECT() *MockChatServiceMockRecorder {
	return m.recorder
}

// CloseChatSession mocks base method.
func (m *MockChatService) CloseChatSession(ctx context.Context, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseChatSession", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseChatSession indicates an expected call of CloseChatSession.
func (mr *MockChatServiceMockRecorder) CloseChatSession(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseChatSession", reflect.TypeOf((*MockChatService)(nil).CloseChatSession), ctx, orderID)
}

// GetChatHistory mocks base method.
func (m *MockChatService) GetChatHistory(ctx context.Context, orderID string) ([]model.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatHistory", ctx, orderID)
	ret0, _ := ret[0].([]model.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatHistory indicates an expected call of GetChatHistory.
func (mr *MockChatServiceMockRecorder) GetChatHistory(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatHistory", reflect.TypeOf((*MockChatService)(nil).GetChatHistory), ctx, orderID)
}

// SendMessage mocks base method.
func (m *MockChatService) SendMessage(ctx context.Context, req model.SendMessageRequest) (*model.SendMessageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, req)
	ret0, _ := ret[0].(*model.SendMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockChatServiceMockRecorder) SendMessage(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockChatService)(nil).SendMessage), ctx, req)
}

// UpdateMessageStatus mocks base method.
func (m *MockChatService) UpdateMessageStatus(ctx context.Context, req model.ReadReceiptRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMessageStatus", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMessageStatus indicates an expected call of UpdateMessageStatus.
func (mr *MockChatServiceMockRecorder) UpdateMessageStatus(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMessageStatus", reflect.TypeOf((*MockChatService)(nil).UpdateMessageStatus), ctx, req)
}
