// Code generated by MockGen. DO NOT EDIT.
// Source: ../../internal/repository/audit-log_repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "furab-backend/services/audit-log-service/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuditLogRepository is a mock of AuditLogRepository interface.
type MockAuditLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuditLogRepositoryMockRecorder
}

// MockAuditLogRepositoryMockRecorder is the mock recorder for MockAuditLogRepository.
type MockAuditLogRepositoryMockRecorder struct {
	mock *MockAuditLogRepository
}

// NewMockAuditLogRepository creates a new mock instance.
func NewMockAuditLogRepository(ctrl *gomock.Controller) *MockAuditLogRepository {
	mock := &MockAuditLogRepository{ctrl: ctrl}
	mock.recorder = &MockAuditLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditLogRepository) EXPECT() *MockAuditLogRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockAuditLogRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAuditLogRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAuditLogRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockAuditLogRepository) GetByID(ctx context.Context, id string) (*model.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAuditLogRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAuditLogRepository)(nil).GetByID), ctx, id)
}

// Save mocks base method.
func (m *MockAuditLogRepository) Save(ctx context.Context, log *model.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAuditLogRepositoryMockRecorder) Save(ctx, log interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAuditLogRepository)(nil).Save), ctx, log)
}

// Search mocks base method.
func (m *MockAuditLogRepository) Search(ctx context.Context, req model.SearchAuditLogRequest) ([]model.AuditLog, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, req)
	ret0, _ := ret[0].([]model.AuditLog)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Search indicates an expected call of Search.
func (mr *MockAuditLogRepositoryMockRecorder) Search(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockAuditLogRepository)(nil).Search), ctx, req)
}

// Update mocks base method.
func (m *MockAuditLogRepository) Update(ctx context.Context, log *model.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAuditLogRepositoryMockRecorder) Update(ctx, log interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAuditLogRepository)(nil).Update), ctx, log)
}
