// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/chat_service.go
//
// Generated by this command:
//
//	mockgen -source internal/service/chat_service.go -destination internal/service/mock_service/mock_chat_service.go -package mock_service
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	model "furab-backend/services/chat-service/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNotificationClient is a mock of NotificationClient interface.
type MockNotificationClient struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationClientMockRecorder
	isgomock struct{}
}

// MockNotificationClientMockRecorder is the mock recorder for MockNotificationClient.
type MockNotificationClientMockRecorder struct {
	mock *MockNotificationClient
}

// NewMockNotificationClient creates a new mock instance.
func NewMockNotificationClient(ctrl *gomock.Controller) *MockNotificationClient {
	mock := &MockNotificationClient{ctrl: ctrl}
	mock.recorder = &MockNotificationClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationClient) EXPECT() *MockNotificationClientMockRecorder {
	return m.recorder
}

// SendNotification mocks base method.
func (m *MockNotificationClient) SendNotification(ctx context.Context, receiverID, messagePreview string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNotification", ctx, receiverID, messagePreview)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendNotification indicates an expected call of SendNotification.
func (mr *MockNotificationClientMockRecorder) SendNotification(ctx, receiverID, messagePreview any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNotification", reflect.TypeOf((*MockNotificationClient)(nil).SendNotification), ctx, receiverID, messagePreview)
}

// MockChatService is a mock of ChatService interface.
type MockChatService struct {
	ctrl     *gomock.Controller
	recorder *MockChatServiceMockRecorder
	isgomock struct{}
}

// MockChatServiceMockRecorder is the mock recorder for MockChatService.
type MockChatServiceMockRecorder struct {
	mock *MockChatService
}

// NewMockChatService creates a new mock instance.
func NewMockChatService(ctrl *gomock.Controller) *MockChatService {
	mock := &MockChatService{ctrl: ctrl}
	mock.recorder = &MockChatServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatService) EXPECT() *MockChatServiceMockRecorder {
	return m.recorder
}

// GetChatHistory mocks base method.
func (m *MockChatService) GetChatHistory(ctx context.Context, orderID string) ([]model.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatHistory", ctx, orderID)
	ret0, _ := ret[0].([]model.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatHistory indicates an expected call of GetChatHistory.
func (mr *MockChatServiceMockRecorder) GetChatHistory(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatHistory", reflect.TypeOf((*MockChatService)(nil).GetChatHistory), ctx, orderID)
}

// SendMessage mocks base method.
func (m *MockChatService) SendMessage(ctx context.Context, req model.SendMessageRequest) (*model.SendMessageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, req)
	ret0, _ := ret[0].(*model.SendMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockChatServiceMockRecorder) SendMessage(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockChatService)(nil).SendMessage), ctx, req)
}

// UpdateReadStatus mocks base method.
func (m *MockChatService) UpdateReadStatus(ctx context.Context, req model.ReadReceiptRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReadStatus", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReadStatus indicates an expected call of UpdateReadStatus.
func (mr *MockChatServiceMockRecorder) UpdateReadStatus(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReadStatus", reflect.TypeOf((*MockChatService)(nil).UpdateReadStatus), ctx, req)
}
