// Code generated by MockGen. DO NOT EDIT.
// Source: ../../internal/repository/rating_repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "furab-backend/services/rating-service/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRatingRepository is a mock of RatingRepository interface.
type MockRatingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRatingRepositoryMockRecorder
}

// MockRatingRepositoryMockRecorder is the mock recorder for MockRatingRepository.
type MockRatingRepositoryMockRecorder struct {
	mock *MockRatingRepository
}

// NewMockRatingRepository creates a new mock instance.
func NewMockRatingRepository(ctrl *gomock.Controller) *MockRatingRepository {
	mock := &MockRatingRepository{ctrl: ctrl}
	mock.recorder = &MockRatingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRatingRepository) EXPECT() *MockRatingRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockRatingRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRatingRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRatingRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockRatingRepository) GetByID(ctx context.Context, id string) (*model.Rating, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Rating)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRatingRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRatingRepository)(nil).GetByID), ctx, id)
}

// Save mocks base method.
func (m *MockRatingRepository) Save(ctx context.Context, rating *model.Rating) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, rating)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRatingRepositoryMockRecorder) Save(ctx, rating interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRatingRepository)(nil).Save), ctx, rating)
}

// Search mocks base method.
func (m *MockRatingRepository) Search(ctx context.Context, req model.SearchRatingRequest) ([]model.Rating, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, req)
	ret0, _ := ret[0].([]model.Rating)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Search indicates an expected call of Search.
func (mr *MockRatingRepositoryMockRecorder) Search(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockRatingRepository)(nil).Search), ctx, req)
}

// Update mocks base method.
func (m *MockRatingRepository) Update(ctx context.Context, rating *model.Rating) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, rating)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRatingRepositoryMockRecorder) Update(ctx, rating interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRatingRepository)(nil).Update), ctx, rating)
}
