// Code generated by MockGen. DO NOT EDIT.
// Source: d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\emergency-service\internal\service\emergency_service.go
//
// Generated by this command:
//
//	mockgen -source=d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\emergency-service\internal\service\emergency_service.go -destination=d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\emergency-service\test\unit\mock\mock_emergency_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "furab-backend/services/emergency-service/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmergencyService is a mock of EmergencyService interface.
type MockEmergencyService struct {
	ctrl     *gomock.Controller
	recorder *MockEmergencyServiceMockRecorder
	isgomock struct{}
}

// MockEmergencyServiceMockRecorder is the mock recorder for MockEmergencyService.
type MockEmergencyServiceMockRecorder struct {
	mock *MockEmergencyService
}

// NewMockEmergencyService creates a new mock instance.
func NewMockEmergencyService(ctrl *gomock.Controller) *MockEmergencyService {
	mock := &MockEmergencyService{ctrl: ctrl}
	mock.recorder = &MockEmergencyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmergencyService) EXPECT() *MockEmergencyServiceMockRecorder {
	return m.recorder
}

// TriggerEmergency mocks base method.
func (m *MockEmergencyService) TriggerEmergency(ctx context.Context, req model.TriggerEmergencyRequest) (*model.TriggerEmergencyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerEmergency", ctx, req)
	ret0, _ := ret[0].(*model.TriggerEmergencyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TriggerEmergency indicates an expected call of TriggerEmergency.
func (mr *MockEmergencyServiceMockRecorder) TriggerEmergency(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerEmergency", reflect.TypeOf((*MockEmergencyService)(nil).TriggerEmergency), ctx, req)
}

// MockLocationClient is a mock of LocationClient interface.
type MockLocationClient struct {
	ctrl     *gomock.Controller
	recorder *MockLocationClientMockRecorder
	isgomock struct{}
}

// MockLocationClientMockRecorder is the mock recorder for MockLocationClient.
type MockLocationClientMockRecorder struct {
	mock *MockLocationClient
}

// NewMockLocationClient creates a new mock instance.
func NewMockLocationClient(ctrl *gomock.Controller) *MockLocationClient {
	mock := &MockLocationClient{ctrl: ctrl}
	mock.recorder = &MockLocationClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocationClient) EXPECT() *MockLocationClientMockRecorder {
	return m.recorder
}

// GetLastLocation mocks base method.
func (m *MockLocationClient) GetLastLocation(ctx context.Context, actorID, actorType string) (*model.EmergencyLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastLocation", ctx, actorID, actorType)
	ret0, _ := ret[0].(*model.EmergencyLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastLocation indicates an expected call of GetLastLocation.
func (mr *MockLocationClientMockRecorder) GetLastLocation(ctx, actorID, actorType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastLocation", reflect.TypeOf((*MockLocationClient)(nil).GetLastLocation), ctx, actorID, actorType)
}

// MockActorClient is a mock of ActorClient interface.
type MockActorClient struct {
	ctrl     *gomock.Controller
	recorder *MockActorClientMockRecorder
	isgomock struct{}
}

// MockActorClientMockRecorder is the mock recorder for MockActorClient.
type MockActorClientMockRecorder struct {
	mock *MockActorClient
}

// NewMockActorClient creates a new mock instance.
func NewMockActorClient(ctrl *gomock.Controller) *MockActorClient {
	mock := &MockActorClient{ctrl: ctrl}
	mock.recorder = &MockActorClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActorClient) EXPECT() *MockActorClientMockRecorder {
	return m.recorder
}

// GetEmergencyContact mocks base method.
func (m *MockActorClient) GetEmergencyContact(ctx context.Context, actorID, actorType string) (*model.EmergencyContact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmergencyContact", ctx, actorID, actorType)
	ret0, _ := ret[0].(*model.EmergencyContact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmergencyContact indicates an expected call of GetEmergencyContact.
func (mr *MockActorClientMockRecorder) GetEmergencyContact(ctx, actorID, actorType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmergencyContact", reflect.TypeOf((*MockActorClient)(nil).GetEmergencyContact), ctx, actorID, actorType)
}

// ValidateActor mocks base method.
func (m *MockActorClient) ValidateActor(ctx context.Context, actorID, actorType string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateActor", ctx, actorID, actorType)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateActor indicates an expected call of ValidateActor.
func (mr *MockActorClientMockRecorder) ValidateActor(ctx, actorID, actorType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateActor", reflect.TypeOf((*MockActorClient)(nil).ValidateActor), ctx, actorID, actorType)
}

// ValidateOrder mocks base method.
func (m *MockActorClient) ValidateOrder(ctx context.Context, orderID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateOrder", ctx, orderID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateOrder indicates an expected call of ValidateOrder.
func (mr *MockActorClientMockRecorder) ValidateOrder(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateOrder", reflect.TypeOf((*MockActorClient)(nil).ValidateOrder), ctx, orderID)
}

// MockNotificationClient is a mock of NotificationClient interface.
type MockNotificationClient struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationClientMockRecorder
	isgomock struct{}
}

// MockNotificationClientMockRecorder is the mock recorder for MockNotificationClient.
type MockNotificationClientMockRecorder struct {
	mock *MockNotificationClient
}

// NewMockNotificationClient creates a new mock instance.
func NewMockNotificationClient(ctrl *gomock.Controller) *MockNotificationClient {
	mock := &MockNotificationClient{ctrl: ctrl}
	mock.recorder = &MockNotificationClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationClient) EXPECT() *MockNotificationClientMockRecorder {
	return m.recorder
}

// SendEmergencyContact mocks base method.
func (m *MockNotificationClient) SendEmergencyContact(ctx context.Context, contact model.EmergencyContact, notification model.EmergencyNotification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmergencyContact", ctx, contact, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmergencyContact indicates an expected call of SendEmergencyContact.
func (mr *MockNotificationClientMockRecorder) SendEmergencyContact(ctx, contact, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmergencyContact", reflect.TypeOf((*MockNotificationClient)(nil).SendEmergencyContact), ctx, contact, notification)
}

// SendNotification mocks base method.
func (m *MockNotificationClient) SendNotification(ctx context.Context, notification model.EmergencyNotification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNotification", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendNotification indicates an expected call of SendNotification.
func (mr *MockNotificationClientMockRecorder) SendNotification(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNotification", reflect.TypeOf((*MockNotificationClient)(nil).SendNotification), ctx, notification)
}
