// Code generated by MockGen. DO NOT EDIT.
// Source: d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\emergency-service\internal\repository\emergency_repository.go
//
// Generated by this command:
//
//	mockgen -source=d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\emergency-service\internal\repository\emergency_repository.go -destination=d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\emergency-service\test\unit\mock\mock_emergency_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "furab-backend/services/emergency-service/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmergencyRepository is a mock of EmergencyRepository interface.
type MockEmergencyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmergencyRepositoryMockRecorder
	isgomock struct{}
}

// MockEmergencyRepositoryMockRecorder is the mock recorder for MockEmergencyRepository.
type MockEmergencyRepositoryMockRecorder struct {
	mock *MockEmergencyRepository
}

// NewMockEmergencyRepository creates a new mock instance.
func NewMockEmergencyRepository(ctrl *gomock.Controller) *MockEmergencyRepository {
	mock := &MockEmergencyRepository{ctrl: ctrl}
	mock.recorder = &MockEmergencyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmergencyRepository) EXPECT() *MockEmergencyRepositoryMockRecorder {
	return m.recorder
}

// SaveEmergencyEvent mocks base method.
func (m *MockEmergencyRepository) SaveEmergencyEvent(ctx context.Context, event model.EmergencyEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEmergencyEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEmergencyEvent indicates an expected call of SaveEmergencyEvent.
func (mr *MockEmergencyRepositoryMockRecorder) SaveEmergencyEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEmergencyEvent", reflect.TypeOf((*MockEmergencyRepository)(nil).SaveEmergencyEvent), ctx, event)
}
