// Code generated by MockGen. DO NOT EDIT.
// Source: d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\location-service\internal\service\location_service.go
//
// Generated by this command:
//
//	mockgen -source=d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\location-service\internal\service\location_service.go -destination=d:\SEMESTER 4\Cloud\furabapps\furab-backend\services\location-service\test\unit\mock\mock_location_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "furab-backend/services/location-service/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDriverServiceClient is a mock of DriverServiceClient interface.
type MockDriverServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockDriverServiceClientMockRecorder
	isgomock struct{}
}

// MockDriverServiceClientMockRecorder is the mock recorder for MockDriverServiceClient.
type MockDriverServiceClientMockRecorder struct {
	mock *MockDriverServiceClient
}

// NewMockDriverServiceClient creates a new mock instance.
func NewMockDriverServiceClient(ctrl *gomock.Controller) *MockDriverServiceClient {
	mock := &MockDriverServiceClient{ctrl: ctrl}
	mock.recorder = &MockDriverServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriverServiceClient) EXPECT() *MockDriverServiceClientMockRecorder {
	return m.recorder
}

// ValidateDriver mocks base method.
func (m *MockDriverServiceClient) ValidateDriver(ctx context.Context, driverID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateDriver", ctx, driverID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateDriver indicates an expected call of ValidateDriver.
func (mr *MockDriverServiceClientMockRecorder) ValidateDriver(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateDriver", reflect.TypeOf((*MockDriverServiceClient)(nil).ValidateDriver), ctx, driverID)
}

// MockLocationService is a mock of LocationService interface.
type MockLocationService struct {
	ctrl     *gomock.Controller
	recorder *MockLocationServiceMockRecorder
	isgomock struct{}
}

// MockLocationServiceMockRecorder is the mock recorder for MockLocationService.
type MockLocationServiceMockRecorder struct {
	mock *MockLocationService
}

// NewMockLocationService creates a new mock instance.
func NewMockLocationService(ctrl *gomock.Controller) *MockLocationService {
	mock := &MockLocationService{ctrl: ctrl}
	mock.recorder = &MockLocationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocationService) EXPECT() *MockLocationServiceMockRecorder {
	return m.recorder
}

// FindNearbyDrivers mocks base method.
func (m *MockLocationService) FindNearbyDrivers(ctx context.Context, req model.SearchDriverRequest) ([]model.DriverLocationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNearbyDrivers", ctx, req)
	ret0, _ := ret[0].([]model.DriverLocationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNearbyDrivers indicates an expected call of FindNearbyDrivers.
func (mr *MockLocationServiceMockRecorder) FindNearbyDrivers(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNearbyDrivers", reflect.TypeOf((*MockLocationService)(nil).FindNearbyDrivers), ctx, req)
}

// GetDriverLocation mocks base method.
func (m *MockLocationService) GetDriverLocation(ctx context.Context, driverID, orderID string) (*model.TrackLocationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDriverLocation", ctx, driverID, orderID)
	ret0, _ := ret[0].(*model.TrackLocationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDriverLocation indicates an expected call of GetDriverLocation.
func (mr *MockLocationServiceMockRecorder) GetDriverLocation(ctx, driverID, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDriverLocation", reflect.TypeOf((*MockLocationService)(nil).GetDriverLocation), ctx, driverID, orderID)
}

// GetEmergencyLocation mocks base method.
func (m *MockLocationService) GetEmergencyLocation(ctx context.Context, driverID, orderID, actorType string) (*model.TrackLocationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmergencyLocation", ctx, driverID, orderID, actorType)
	ret0, _ := ret[0].(*model.TrackLocationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmergencyLocation indicates an expected call of GetEmergencyLocation.
func (mr *MockLocationServiceMockRecorder) GetEmergencyLocation(ctx, driverID, orderID, actorType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmergencyLocation", reflect.TypeOf((*MockLocationService)(nil).GetEmergencyLocation), ctx, driverID, orderID, actorType)
}

// UpdateDriverLocation mocks base method.
func (m *MockLocationService) UpdateDriverLocation(ctx context.Context, req model.UpdateLocationRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDriverLocation", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDriverLocation indicates an expected call of UpdateDriverLocation.
func (mr *MockLocationServiceMockRecorder) UpdateDriverLocation(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDriverLocation", reflect.TypeOf((*MockLocationService)(nil).UpdateDriverLocation), ctx, req)
}

// UpdateDriverStatus mocks base method.
func (m *MockLocationService) UpdateDriverStatus(ctx context.Context, req model.UpdateStatusRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDriverStatus", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDriverStatus indicates an expected call of UpdateDriverStatus.
func (mr *MockLocationServiceMockRecorder) UpdateDriverStatus(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDriverStatus", reflect.TypeOf((*MockLocationService)(nil).UpdateDriverStatus), ctx, req)
}
