// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/otp_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/otp_repository.go -destination=internal/repository/mock/otp_repository_mock.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	"context"
	"reflect"

	"furab-backend/services/otp-service/internal/model"

	"go.uber.org/mock/gomock"
)

// MockOTPRepository is a mock of OTPRepository interface.
type MockOTPRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOTPRepositoryMockRecorder
	isgomock struct{}
}

// MockOTPRepositoryMockRecorder is the mock recorder for MockOTPRepository.
type MockOTPRepositoryMockRecorder struct {
	mock *MockOTPRepository
}

// NewMockOTPRepository creates a new mock instance.
func NewMockOTPRepository(ctrl *gomock.Controller) *MockOTPRepository {
	mock := &MockOTPRepository{ctrl: ctrl}
	mock.recorder = &MockOTPRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOTPRepository) EXPECT() *MockOTPRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockOTPRepository) Save(ctx context.Context, otp *model.OTP) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, otp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockOTPRepositoryMockRecorder) Save(ctx, otp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockOTPRepository)(nil).Save), ctx, otp)
}

// GetByTarget mocks base method.
func (m *MockOTPRepository) GetByTarget(ctx context.Context, target string) (*model.OTP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTarget", ctx, target)
	ret0, _ := ret[0].(*model.OTP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTarget indicates an expected call of GetByTarget.
func (mr *MockOTPRepositoryMockRecorder) GetByTarget(ctx, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTarget", reflect.TypeOf((*MockOTPRepository)(nil).GetByTarget), ctx, target)
}

// Delete mocks base method.
func (m *MockOTPRepository) Delete(ctx context.Context, otpID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, otpID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOTPRepositoryMockRecorder) Delete(ctx, otpID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOTPRepository)(nil).Delete), ctx, otpID)
}
