// Code generated by MockGen. DO NOT EDIT.
// Source: furab-backend/services/promo-service/internal/client (interfaces: OrderClient)
//
// Generated by this command:
//
//	mockgen -destination=test\mock\order_client_mock.go -package=mock furab-backend/services/promo-service/internal/client OrderClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrderClient is a mock of OrderClient interface.
type MockOrderClient struct {
	ctrl     *gomock.Controller
	recorder *MockOrderClientMockRecorder
	isgomock struct{}
}

// MockOrderClientMockRecorder is the mock recorder for MockOrderClient.
type MockOrderClientMockRecorder struct {
	mock *MockOrderClient
}

// NewMockOrderClient creates a new mock instance.
func NewMockOrderClient(ctrl *gomock.Controller) *MockOrderClient {
	mock := &MockOrderClient{ctrl: ctrl}
	mock.recorder = &MockOrderClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderClient) EXPECT() *MockOrderClientMockRecorder {
	return m.recorder
}

// ValidateOrderPromo mocks base method.
func (m *MockOrderClient) ValidateOrderPromo(ctx context.Context, orderID, promoCode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateOrderPromo", ctx, orderID, promoCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateOrderPromo indicates an expected call of ValidateOrderPromo.
func (mr *MockOrderClientMockRecorder) ValidateOrderPromo(ctx, orderID, promoCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateOrderPromo", reflect.TypeOf((*MockOrderClient)(nil).ValidateOrderPromo), ctx, orderID, promoCode)
}
