// Code generated by MockGen. DO NOT EDIT.
// Source: furab-backend/services/promo-service/internal/repository (interfaces: PromoRepository)
//
// Generated by this command:
//
//	mockgen -destination=test\mock\promo_repository_mock.go -package=mock furab-backend/services/promo-service/internal/repository PromoRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "furab-backend/services/promo-service/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPromoRepository is a mock of PromoRepository interface.
type MockPromoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPromoRepositoryMockRecorder
	isgomock struct{}
}

// MockPromoRepositoryMockRecorder is the mock recorder for MockPromoRepository.
type MockPromoRepositoryMockRecorder struct {
	mock *MockPromoRepository
}

// NewMockPromoRepository creates a new mock instance.
func NewMockPromoRepository(ctrl *gomock.Controller) *MockPromoRepository {
	mock := &MockPromoRepository{ctrl: ctrl}
	mock.recorder = &MockPromoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromoRepository) EXPECT() *MockPromoRepositoryMockRecorder {
	return m.recorder
}

// GetPromoByCode mocks base method.
func (m *MockPromoRepository) GetPromoByCode(ctx context.Context, promoCode string) (*model.Promo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromoByCode", ctx, promoCode)
	ret0, _ := ret[0].(*model.Promo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromoByCode indicates an expected call of GetPromoByCode.
func (mr *MockPromoRepositoryMockRecorder) GetPromoByCode(ctx, promoCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromoByCode", reflect.TypeOf((*MockPromoRepository)(nil).GetPromoByCode), ctx, promoCode)
}

// IncrementUsage mocks base method.
func (m *MockPromoRepository) IncrementUsage(ctx context.Context, promoID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementUsage", ctx, promoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementUsage indicates an expected call of IncrementUsage.
func (mr *MockPromoRepositoryMockRecorder) IncrementUsage(ctx, promoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementUsage", reflect.TypeOf((*MockPromoRepository)(nil).IncrementUsage), ctx, promoID)
}
