// Code generated by MockGen. DO NOT EDIT.
// Source: furab-backend/services/promo-service/internal/client (interfaces: UserClient)
//
// Generated by this command:
//
//	mockgen -destination=test\mock\user_client_mock.go -package=mock furab-backend/services/promo-service/internal/client UserClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserClient is a mock of UserClient interface.
type MockUserClient struct {
	ctrl     *gomock.Controller
	recorder *MockUserClientMockRecorder
	isgomock struct{}
}

// MockUserClientMockRecorder is the mock recorder for MockUserClient.
type MockUserClientMockRecorder struct {
	mock *MockUserClient
}

// NewMockUserClient creates a new mock instance.
func NewMockUserClient(ctrl *gomock.Controller) *MockUserClient {
	mock := &MockUserClient{ctrl: ctrl}
	mock.recorder = &MockUserClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserClient) EXPECT() *MockUserClientMockRecorder {
	return m.recorder
}

// ValidateUserPromo mocks base method.
func (m *MockUserClient) ValidateUserPromo(ctx context.Context, userID, promoCode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateUserPromo", ctx, userID, promoCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateUserPromo indicates an expected call of ValidateUserPromo.
func (mr *MockUserClientMockRecorder) ValidateUserPromo(ctx, userID, promoCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUserPromo", reflect.TypeOf((*MockUserClient)(nil).ValidateUserPromo), ctx, userID, promoCode)
}
