// Code generated by MockGen. DO NOT EDIT.
// Source: furab-backend/services/payment-service/internal/repository (interfaces: PaymentRepository)
//
// Generated by this command:
//
//	mockgen -destination=test\unit\mock\payment_repository_mock.go -package=mock furab-backend/services/payment-service/internal/repository PaymentRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "furab-backend/services/payment-service/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentRepository is a mock of PaymentRepository interface.
type MockPaymentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentRepositoryMockRecorder
	isgomock struct{}
}

// MockPaymentRepositoryMockRecorder is the mock recorder for MockPaymentRepository.
type MockPaymentRepositoryMockRecorder struct {
	mock *MockPaymentRepository
}

// NewMockPaymentRepository creates a new mock instance.
func NewMockPaymentRepository(ctrl *gomock.Controller) *MockPaymentRepository {
	mock := &MockPaymentRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentRepository) EXPECT() *MockPaymentRepositoryMockRecorder {
	return m.recorder
}

// CreatePayment mocks base method.
func (m *MockPaymentRepository) CreatePayment(ctx context.Context, p *model.Payment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockPaymentRepositoryMockRecorder) CreatePayment(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockPaymentRepository)(nil).CreatePayment), ctx, p)
}

// CreatePaymentLog mocks base method.
func (m *MockPaymentRepository) CreatePaymentLog(ctx context.Context, paymentID string, status model.PaymentStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePaymentLog", ctx, paymentID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePaymentLog indicates an expected call of CreatePaymentLog.
func (mr *MockPaymentRepositoryMockRecorder) CreatePaymentLog(ctx, paymentID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePaymentLog", reflect.TypeOf((*MockPaymentRepository)(nil).CreatePaymentLog), ctx, paymentID, status)
}

// GetPaymentByID mocks base method.
func (m *MockPaymentRepository) GetPaymentByID(ctx context.Context, paymentID string) (*model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentByID", ctx, paymentID)
	ret0, _ := ret[0].(*model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentByID indicates an expected call of GetPaymentByID.
func (mr *MockPaymentRepositoryMockRecorder) GetPaymentByID(ctx, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentByID", reflect.TypeOf((*MockPaymentRepository)(nil).GetPaymentByID), ctx, paymentID)
}

// GetPaymentByIdempotencyKey mocks base method.
func (m *MockPaymentRepository) GetPaymentByIdempotencyKey(ctx context.Context, key string) (*model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentByIdempotencyKey", ctx, key)
	ret0, _ := ret[0].(*model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentByIdempotencyKey indicates an expected call of GetPaymentByIdempotencyKey.
func (mr *MockPaymentRepositoryMockRecorder) GetPaymentByIdempotencyKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentByIdempotencyKey", reflect.TypeOf((*MockPaymentRepository)(nil).GetPaymentByIdempotencyKey), ctx, key)
}

// UpdatePaymentStatus mocks base method.
func (m *MockPaymentRepository) UpdatePaymentStatus(ctx context.Context, paymentID string, status model.PaymentStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaymentStatus", ctx, paymentID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePaymentStatus indicates an expected call of UpdatePaymentStatus.
func (mr *MockPaymentRepositoryMockRecorder) UpdatePaymentStatus(ctx, paymentID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaymentStatus", reflect.TypeOf((*MockPaymentRepository)(nil).UpdatePaymentStatus), ctx, paymentID, status)
}
