// Code generated by MockGen. DO NOT EDIT.
// Source: furab-backend/services/payment-service/internal/service (interfaces: PricingClient,PromoClient,WalletClient,SettlementClient)
//
// Generated by this command:
//
//	mockgen -destination=test\unit\mock\service_mock.go -package=mock furab-backend/services/payment-service/internal/service PricingClient,PromoClient,WalletClient,SettlementClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPricingClient is a mock of PricingClient interface.
type MockPricingClient struct {
	ctrl     *gomock.Controller
	recorder *MockPricingClientMockRecorder
	isgomock struct{}
}

// MockPricingClientMockRecorder is the mock recorder for MockPricingClient.
type MockPricingClientMockRecorder struct {
	mock *MockPricingClient
}

// NewMockPricingClient creates a new mock instance.
func NewMockPricingClient(ctrl *gomock.Controller) *MockPricingClient {
	mock := &MockPricingClient{ctrl: ctrl}
	mock.recorder = &MockPricingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPricingClient) EXPECT() *MockPricingClientMockRecorder {
	return m.recorder
}

// GetTotalAmount mocks base method.
func (m *MockPricingClient) GetTotalAmount(ctx context.Context, orderID string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalAmount", ctx, orderID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalAmount indicates an expected call of GetTotalAmount.
func (mr *MockPricingClientMockRecorder) GetTotalAmount(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalAmount", reflect.TypeOf((*MockPricingClient)(nil).GetTotalAmount), ctx, orderID)
}

// MockPromoClient is a mock of PromoClient interface.
type MockPromoClient struct {
	ctrl     *gomock.Controller
	recorder *MockPromoClientMockRecorder
	isgomock struct{}
}

// MockPromoClientMockRecorder is the mock recorder for MockPromoClient.
type MockPromoClientMockRecorder struct {
	mock *MockPromoClient
}

// NewMockPromoClient creates a new mock instance.
func NewMockPromoClient(ctrl *gomock.Controller) *MockPromoClient {
	mock := &MockPromoClient{ctrl: ctrl}
	mock.recorder = &MockPromoClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromoClient) EXPECT() *MockPromoClientMockRecorder {
	return m.recorder
}

// ApplyPromo mocks base method.
func (m *MockPromoClient) ApplyPromo(ctx context.Context, promoCode string, totalAmount float64) (float64, float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyPromo", ctx, promoCode, totalAmount)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(float64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ApplyPromo indicates an expected call of ApplyPromo.
func (mr *MockPromoClientMockRecorder) ApplyPromo(ctx, promoCode, totalAmount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyPromo", reflect.TypeOf((*MockPromoClient)(nil).ApplyPromo), ctx, promoCode, totalAmount)
}

// MockWalletClient is a mock of WalletClient interface.
type MockWalletClient struct {
	ctrl     *gomock.Controller
	recorder *MockWalletClientMockRecorder
	isgomock struct{}
}

// MockWalletClientMockRecorder is the mock recorder for MockWalletClient.
type MockWalletClientMockRecorder struct {
	mock *MockWalletClient
}

// NewMockWalletClient creates a new mock instance.
func NewMockWalletClient(ctrl *gomock.Controller) *MockWalletClient {
	mock := &MockWalletClient{ctrl: ctrl}
	mock.recorder = &MockWalletClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletClient) EXPECT() *MockWalletClientMockRecorder {
	return m.recorder
}

// CreditBalance mocks base method.
func (m *MockWalletClient) CreditBalance(ctx context.Context, userID string, amount float64, reference string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreditBalance", ctx, userID, amount, reference)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreditBalance indicates an expected call of CreditBalance.
func (mr *MockWalletClientMockRecorder) CreditBalance(ctx, userID, amount, reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreditBalance", reflect.TypeOf((*MockWalletClient)(nil).CreditBalance), ctx, userID, amount, reference)
}

// DeductBalance mocks base method.
func (m *MockWalletClient) DeductBalance(ctx context.Context, userID string, amount float64, reference string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeductBalance", ctx, userID, amount, reference)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeductBalance indicates an expected call of DeductBalance.
func (mr *MockWalletClientMockRecorder) DeductBalance(ctx, userID, amount, reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeductBalance", reflect.TypeOf((*MockWalletClient)(nil).DeductBalance), ctx, userID, amount, reference)
}

// LockBalance mocks base method.
func (m *MockWalletClient) LockBalance(ctx context.Context, userID string, amount float64, reference string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockBalance", ctx, userID, amount, reference)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockBalance indicates an expected call of LockBalance.
func (mr *MockWalletClientMockRecorder) LockBalance(ctx, userID, amount, reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockBalance", reflect.TypeOf((*MockWalletClient)(nil).LockBalance), ctx, userID, amount, reference)
}

// UnlockBalance mocks base method.
func (m *MockWalletClient) UnlockBalance(ctx context.Context, userID string, amount float64, reference string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlockBalance", ctx, userID, amount, reference)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlockBalance indicates an expected call of UnlockBalance.
func (mr *MockWalletClientMockRecorder) UnlockBalance(ctx, userID, amount, reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockBalance", reflect.TypeOf((*MockWalletClient)(nil).UnlockBalance), ctx, userID, amount, reference)
}

// MockSettlementClient is a mock of SettlementClient interface.
type MockSettlementClient struct {
	ctrl     *gomock.Controller
	recorder *MockSettlementClientMockRecorder
	isgomock struct{}
}

// MockSettlementClientMockRecorder is the mock recorder for MockSettlementClient.
type MockSettlementClientMockRecorder struct {
	mock *MockSettlementClient
}

// NewMockSettlementClient creates a new mock instance.
func NewMockSettlementClient(ctrl *gomock.Controller) *MockSettlementClient {
	mock := &MockSettlementClient{ctrl: ctrl}
	mock.recorder = &MockSettlementClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettlementClient) EXPECT() *MockSettlementClientMockRecorder {
	return m.recorder
}

// TriggerSettlement mocks base method.
func (m *MockSettlementClient) TriggerSettlement(ctx context.Context, paymentID, orderID string, finalAmount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerSettlement", ctx, paymentID, orderID, finalAmount)
	ret0, _ := ret[0].(error)
	return ret0
}

// TriggerSettlement indicates an expected call of TriggerSettlement.
func (mr *MockSettlementClientMockRecorder) TriggerSettlement(ctx, paymentID, orderID, finalAmount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerSettlement", reflect.TypeOf((*MockSettlementClient)(nil).TriggerSettlement), ctx, paymentID, orderID, finalAmount)
}
